### ISSUE TITLE
LanguageGame crashes when on hard mode

### ISSUE THREAD

**Issue by waldbaan** [Stensel8/Half-a-Minute-IT-Madness-Android#9]
When playing the language test (in german) on hard mode, the game crashes.

**Comment by Stensel8** [comment]
Seems like this is also occurring on the medium game aswell. Only the easy game does seem to be functioning properly. I'm going to investigate this ;(

**Comment by Stensel8** [comment]
@waldbaan, help wanted.

**Comment by Stensel8** [comment]
Think i've found a solution for this. I'm going to test this in the upcoming days and will release it within a few days / next weekend.
